# Generated by Django 5.1.1 on 2024-10-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('skill_1', models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')])),
                ('skill_2', models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')])),
                ('skill_3', models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')])),
                ('skill_4', models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')])),
                ('skill_5', models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')])),
                ('qualifications', models.TextField()),
                ('preferences', models.CharField(max_length=500)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
            ],
        ),
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(max_length=50)),
                ('companyname', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('jobdescription', models.CharField(max_length=2000)),
                ('dateposted', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('location', models.TextField()),
            ],
        ),
    ]
