# Generated by Django 5.1.1 on 2024-10-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobListings',
            new_name='JobDetails',
        ),
    ]
