# Generated by Django 5.1.1 on 2024-12-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0002_applicantdetails_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRL.applicantdetails')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRL.jobdetails')),
            ],
            options={
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
