# Generated by Django 5.1.1 on 2024-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0002_rename_joblistings_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='jobtype',
            field=models.TextField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Seasonal', 'Seasonal')], default='Full Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='preferences',
            field=models.TextField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('', ''), ('null', 'null')]),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='skill_3',
            field=models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing'), ('null', 'null')]),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='skill_4',
            field=models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing'), ('null', 'null')]),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='skill_5',
            field=models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing'), ('null', 'null')]),
        ),
    ]
