# Generated by Django 5.1.1 on 2024-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0003_jobdetails_jobtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='dateposted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
