# Generated by Django 5.1.1 on 2024-12-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0004_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobprimaryskill',
            field=models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Managerial Experience', 'Managerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')]),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobsecondaryskill',
            field=models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Managerial Experience', 'Managerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Managerial Experience', 'Managerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')], max_length=50, unique=True),
        ),
    ]
