# Generated by Django 5.1.1 on 2024-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0004_alter_jobdetails_dateposted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='recruitmentstage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
