# Generated by Django 5.1.1 on 2024-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0005_applicantdetails_recruitmentstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='recruitmentstage',
            field=models.IntegerField(null=True),
        ),
    ]
