# Generated by Django 5.1.1 on 2024-10-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0006_alter_applicantdetails_recruitmentstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='recruitmentstage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
