# Generated by Django 5.1.1 on 2024-10-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0007_alter_applicantdetails_recruitmentstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantdetails',
            name='recruitmentstage',
        ),
    ]
