# Generated by Django 5.1.2 on 2024-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0008_remove_applicantdetails_recruitmentstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='recruitmenttracker',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
