# Generated by Django 5.1.2 on 2024-10-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0009_applicantdetails_recruitmenttracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='jobprimaryskill',
            field=models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')], default='Technological Expereince'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='jobsecondaryskill',
            field=models.TextField(choices=[('Adult Social Care', 'Adult Social Care'), ('Child Social Care', 'Child Social Care'), ('Elderly Social Care', 'Elderly Social Care'), ('Hospital/GP Experience', 'Hospital/GP Experience'), ('Manegerial Experience', 'Manegerial Experience'), ('Technological Experience', 'Technological Experience'), ('Physiotherapy', 'Physiotherapy'), ('Doctorate', 'Doctorate'), ('Surgeon', 'Surgeon'), ('Nursing', 'Nursing')], default='Technological Experience'),
            preserve_default=False,
        ),
    ]
