# Generated by Django 5.1.2 on 2024-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0010_jobdetails_jobprimaryskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='jobsuitablefor',
            field=models.TextField(default='ismail@zaffar.com'),
            preserve_default=False,
        ),
    ]
