# Generated by Django 5.1.1 on 2024-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRL', '0011_jobdetails_jobsuitablefor'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='accepted_job',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='jobsuitablefor',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='jobsuitablefor',
            field=models.ManyToManyField(blank=True, related_name='job_suitable_for', to='TRL.applicantdetails'),
        ),
    ]
